# for dev/master branch
-
  version: 3.1.2.{build}
  pull_requests:
    do_not_increment_build_number: true
  branches:
    only:
    - dev
    - master
  skip_tags: true
  image: Visual Studio 2015
  configuration: Debug
  platform: Any CPU
  build:
    verbosity: minimal

# for release branch
-
  version: 3.1.2.{build}
  pull_requests:
    do_not_increment_build_number: true
  branches:
    only:
    - release
  skip_tags: true
  image: Visual Studio 2015
  configuration: Release
  platform: Any CPU
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
  environment:
    github_auth_token:
      secure: 3tp7rCl4cvk/WDYBaeodIlmalNiYVWQYxE1wmVU7aMbkMKP0WtlMjjOU2yhX0D4n
  build_script:
  - cmd: tools\nuget restore AppForSharePointOnlineWebToolkit.sln
  - cmd: msbuild "src\AppForSharePointOnlineWebToolkit\AppForSharePointOnlineWebToolkit.csproj" /t:ReBuild /p:Configuration=Release;TargetFrameworkVersion=v4.5;DefineConstants="TRACE;NET45";OutPutPath=bin\Release\net45\  after_test:
  - cmd: tools\nuget pack "src\AppForSharePointOnlineWebToolkit\AppForSharePointOnlineWebToolkit.csproj" -OutputDirectory build -Version $env:appveyor_build_version
  artifacts:
  - path: '**\*.nupkg'
    name: AppForSharePointOnlineWebToolkit
  deploy:
  - provider: NuGet
    api_key:
      secure: ZdI7BA2YRQg/yRMPbRGTTJeGWj3X3o8kNhf4LeA5YkV072GpmKwQ3aW+KVgMbkZX
    artifact: AppForSharePointOnlineWebToolkit
    on:
      branch: release
      platform: Any CPU
      configuration: Release
  after_deploy:
  - cmd: git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:github_auth_token):x-oauth-basic@github.com`n"
  - cmd: git push origin --delete release
